name: pareidolia
description: A library to generate random noise images.
version: 1.0.0
repository: https://github.com/tytydraco/pareidolia

environment:
  sdk: ^3.6.0

dependencies:
  image: ^4.5.2

dev_dependencies:
  very_good_analysis: any
